spring:
  application:
    name: library-app

  datasource:
    url: jdbc:mysql://localhost:3306/librarydb?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: spring
    password: spring1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


# ???? ??
logging:
  level:
    org.springframework.jdbc: DEBUG
    org.springframework.data.jdbc: DEBUG
