name: Deploy to AWS EC2

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      # Node.js 환경 설정 (프론트엔드 빌드용)
      #- name: Setup Node.js
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: 20

      # 프론트엔드 의존성 설치 및 빌드
      #- name: Install frontend dependencies
      #  run: |
      #    cd frontend
      #    npm install
      #    npm run build

      # Gradle Wrapper 실행 권한 부여
      - name: Grant execute permission for Gradle Wrapper
        run: chmod +x ./gradlew

      - name: Build Backend JAR
        run: ./gradlew build -x test

      - name: Copy Backend JAR to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          source: "build/libs/BasicProject-0.0.1-SNAPSHOT.jar"
          target: "/home/ec2-user/app/backend"

      - name: Deploy to EC2 #배포
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_KEY }}
          script: |
            # Backend 배포
            cd /home/ec2-user/app/backend
            pkill -f "java -jar BasicProject-0.0.1-SNAPSHOT.jar" || true
            # java프로세스만 죽이기.
            nohup java -jar BasicProject-0.0.1-SNAPSHOT.jar > backend.log 2>&1 < /dev/null &

            # Frontend 배포
            # cd /home/ec2-user/app/frontend
            # pkill -f 'npm' || true
            # cp -r ~/frontend/* . 
            # npm install
            # nohup npm run start > frontend.log 2>&1 &
